### ISSUE TITLE
Cover Images / Trailers

### ISSUE THREAD

**Issue by djvalley** [kbestul2/cvtc-agile-group-project#2]
For the CoverImgUrl it will require you to concat a base URL with the conventions that follow depending on the size of the image that is required. They are the width in pixels.

`String string = "https://image.tmdb.org/t/p/" + INSERT_SIZE + CoverImgUrl`

INSERT_SIZE = [ w92, w154, w185, w342, w500, w780, original ]

For movie trailers, the DB has a key stored as a string that will be something like this "RFuZhw5b1KA"
This key will be used to embed youtube videos with the base url of 
`https://www.youtube.com/watch?v=`

`String trailerUrl = "https://www.youtube.com/watch?v=" + TrailerKey`

**Comment by kbestul2** [comment]
I don't think this would work for how the results are being generated on the page. This is how the jstl looks in the .jsp:

```
<c:choose>  

    <c:when test="${empty movies}">  

        <p>Sorry, the list of movies is empty.</p>  

    </c:when>  

    <c:otherwise>  

        <c:forEach var="movie" items="${movies}">  

            <h2>${movie.title}</h2>  

            <p>  

                Original Release: ${movie.releaseDate}<br>  

                Stream Release: ${movie.streamDate}<br>  

                Rating: ${movie.contentRating}<br>  

                Length: ${movie.length} minutes<br>  

                Description: ${movie.description}<br>  

                Rating: ${movie.userRating}<br>  

                coverImgUrl: https://image.tmdb.org/t/p/ ??? ${movie.coverImgUrl}<br>  

                trailerUrl: https://www.youtube.com/watch?v=${movie.trailerKey}<br>  

                platform: ${movie.platform}  

            </p>  

        </c:forEach>  

    </c:otherwise>  

</c:choose>  
```

The URL strings ("https://www.youtube.com/watch?v=" and "https://image.tmdb.org/t/p/" wouldn't need to be stored anywhere because they can just be typed once inside the jstl tags and will be generated with each new movie listing.

Because of the way the movies get generated, an INSERT_SIZE can't be customized for each movie. All of the movies would have to have the same INSERT_SIZE. If a certain size works best for a certain movie, they would have to be connected in the database.

I can however, pass a parameter in the url to select one INSERT_SIZE and then make all generated movies use that same size. OR I could generate a smaller image size on the page that is in an ```<a>``` tag that links to a larger version of the image.

It's possible that I am misunderstanding the intent behind the INSERT_SIZE. Let me know how you see it being implemented.

**Comment by kbestul2** [comment]
Never mind the part about the URL strings, I see that it makes more sense to concatenate the base and key and then pass that in the constructor before I create a new object. I was misunderstanding where this concatenation would take place. My only concern now is that this approach locks us into using YouTube for trailers. Also the part about INSERT_SIZE is still unclear to me. I get that it is part of the image url that determines the size of the image, but I don't understand why or where the different image sizes would be used.

**Comment by kbestul2** [comment]
I am using the 500w images for each movie object. The images displayed on the page can be scaled using CSS. If this resolution is to low/high, it can be adjusted by modifying the index of "INSERT_SIZE".
```
while (resultSet.next()) {
	...
	final String coverImgUrl = "https://image.tmdb.org/t/p/" + INSERT_SIZE[4] + resultSet.getString("CoverImgUrl");
	...	
	movies.add(new Movie(title, releaseDate, streamDate, genres, contentRating, length, description, userRating, coverImgUrl, trailerUrl, platform));
}
```
